# Generated by Django 3.0.10 on 2020-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201026_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='accounts/user.png', upload_to='accounts/avatar/%Y/%m/%d'),
        ),
    ]
