# Generated by Django 3.0.10 on 2020-11-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_file',
        ),
    ]
